#!/bin/bash
# create_pr.sh — 推送分支并创建 GitHub PR
#
# 用法:
#   bash create_pr.sh <repo-path> <branch> <req-id> <title> [description] [related-pr-urls] [base-branch] [service-name]
set -euo pipefail

REPO_PATH="${1:?Usage: create_pr.sh <repo-path> <branch> <req-id> <title> [description] [related-pr-urls] [base-branch] [service-name]}"
BRANCH="${2:?Missing branch name}"
REQ_ID="${3:?Missing req-id}"
TITLE="${4:?Missing PR title}"
DESCRIPTION="${5:-}"
RELATED_PRS="${6:-}"
BASE_BRANCH="${7:-main}"
SERVICE_NAME="${8:-}"

if [ ! -d "$REPO_PATH" ]; then
    echo "ERROR: repo path does not exist: $REPO_PATH"
    exit 2
fi

cd "$REPO_PATH"

# ── 前置条件：质量门禁必须已通过 ────────────────────────────────
STATE_FILE="/tmp/.claude_hub_active"
if [ -f "$STATE_FILE" ]; then
    if [ -n "$SERVICE_NAME" ]; then
        STEP3_KEY="svc_${SERVICE_NAME}_step3"
    else
        STEP3_KEY="step3_quality_gate"
    fi
    STEP3_VAL=$(grep "^${STEP3_KEY}:" "$STATE_FILE" 2>/dev/null | cut -d' ' -f2- | tr -d '[:space:]' || echo "")
    if [ "$STEP3_VAL" = "BLOCKED" ]; then
        echo "ERROR: 质量门禁未通过（${STEP3_KEY}: BLOCKED），禁止创建 PR。"
        echo "必须先修复问题并重跑 quality_gate.sh 直到 verdict: PASSED"
        exit 1
    elif [ -z "$STEP3_VAL" ]; then
        echo "ERROR: 质量门禁尚未运行（${STEP3_KEY} 不存在）。必须先运行 quality_gate.sh（Step 3）。"
        exit 1
    fi
fi

# ── 检查 gh CLI 可用性 ────────────────────────────────────────
CAN_CREATE_PR="false"

if command -v gh &>/dev/null; then
    if gh auth status &>/dev/null; then
        CAN_CREATE_PR="true"
    else
        echo "NOTE: gh installed but not authenticated"
        echo "      Run: gh auth login"
        echo "      Falling back to push-only mode"
        echo ""
    fi
else
    echo "NOTE: gh CLI not installed, falling back to push-only mode"
    echo "      Install: brew install gh"
    echo ""
fi

# ── 检查当前分支 ─────────────────────────────────────────────
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "")
if [ "$CURRENT_BRANCH" != "$BRANCH" ]; then
    echo "WARNING: current branch '${CURRENT_BRANCH}' != expected '${BRANCH}'"
    echo "Switching to ${BRANCH}..."
    git checkout "$BRANCH" 2>/dev/null || {
        echo "ERROR: cannot switch to branch ${BRANCH}"
        exit 1
    }
fi

# ── 校验目标分支存在 ─────────────────────────────────────────
if ! git rev-parse "origin/${BASE_BRANCH}" &>/dev/null; then
    echo "ERROR: target branch 'origin/${BASE_BRANCH}' does not exist."
    echo "       Available remote branches:"
    git branch -r 2>/dev/null | head -10 | sed 's/^/         /'
    exit 1
fi

# ── 检查有无 commit ──────────────────────────────────────────
COMMIT_COUNT=$(git rev-list --count "origin/${BASE_BRANCH}..${BRANCH}" 2>/dev/null || echo "0")
if [ "$COMMIT_COUNT" -eq 0 ]; then
    echo "ERROR: no commits on ${BRANCH} ahead of origin/${BASE_BRANCH}"
    exit 1
fi

# ── Push ─────────────────────────────────────────────────────
echo "Pushing ${BRANCH} to origin..."
PUSH_OUTPUT=$(git push origin "$BRANCH" -u 2>&1) || {
    echo "ERROR: push failed"
    echo "$PUSH_OUTPUT"
    exit 1
}
echo "Push OK"

# ── 构建 PR 描述 ─────────────────────────────────────────────
PR_TITLE="[${REQ_ID}] ${TITLE}"

PR_BODY="## Summary

${DESCRIPTION:-_No description provided._}

## Info

- ID: \`${REQ_ID}\`
- Branch: \`${BRANCH}\`
- Commits: ${COMMIT_COUNT}
"

if [ -n "$RELATED_PRS" ]; then
    PR_BODY="${PR_BODY}
## Related PRs

"
    IFS=',' read -ra PR_ARRAY <<< "$RELATED_PRS"
    for pr_url in "${PR_ARRAY[@]}"; do
        pr_url=$(echo "$pr_url" | xargs)
        PR_BODY="${PR_BODY}- ${pr_url}
"
    done
fi

PR_BODY="${PR_BODY}
---
_Generated by Personal Harness Hub_"

# ── 创建 PR 或输出链接 ────────────────────────────────────────
if [ "$CAN_CREATE_PR" = "true" ]; then
    echo "Creating PR via gh..."
    PR_URL=$(gh pr create \
        --title "$PR_TITLE" \
        --body "$PR_BODY" \
        --base "$BASE_BRANCH" \
        --label "agent-generated" 2>&1) || {
        echo "WARNING: gh PR creation failed, branch is pushed"
        echo "$PR_URL"
        echo ""
        echo "=== PR CREATED ==="
        echo "mode: push-only (gh failed)"
        echo "repo: $(basename "$REPO_PATH")"
        echo "branch: ${BRANCH}"
        echo "title: ${PR_TITLE}"
        echo "commits: ${COMMIT_COUNT}"
        echo "=== END ==="
        exit 0
    }

    EXTRACTED_URL=$(echo "$PR_URL" | grep -oE 'https?://[^ ]+' | head -1 || echo "$PR_URL")

    echo ""
    echo "=== PR CREATED ==="
    echo "mode: gh"
    echo "repo: $(basename "$REPO_PATH")"
    echo "branch: ${BRANCH}"
    echo "title: ${PR_TITLE}"
    echo "url: ${EXTRACTED_URL}"
    echo "commits: ${COMMIT_COUNT}"
    echo "=== END ==="
else
    # 构建 GitHub PR URL
    REMOTE_URL=$(git remote get-url origin 2>/dev/null || echo "")
    GH_REPO=$(echo "$REMOTE_URL" | sed -E 's#^(https://github.com/|git@github.com:)##; s#\.git$##')
    CREATE_URL="https://github.com/${GH_REPO}/compare/${BASE_BRANCH}...${BRANCH}?expand=1"

    echo ""
    echo "=== PR CREATED ==="
    echo "mode: push-only"
    echo "repo: $(basename "$REPO_PATH")"
    echo "branch: ${BRANCH}"
    echo "title: ${PR_TITLE}"
    echo "commits: ${COMMIT_COUNT}"
    echo "create_pr_url: ${CREATE_URL}"
    echo "=== END ==="
fi

# ── 写入状态标记 ─────────────────────────────────────────────
STATE_FILE="/tmp/.claude_hub_active"
if [ -f "$STATE_FILE" ]; then
    MODE=$( [ "$CAN_CREATE_PR" = "true" ] && echo "gh" || echo "push-only" )
    if [ -n "$SERVICE_NAME" ]; then
        MARKER_KEY="svc_${SERVICE_NAME}_step5"
    else
        MARKER_KEY="step5_pr_created"
    fi
    if grep -q "^${MARKER_KEY}:" "$STATE_FILE" 2>/dev/null; then
        sed -i.bak "s/^${MARKER_KEY}:.*/${MARKER_KEY}: ${MODE}/" "$STATE_FILE"
        rm -f "${STATE_FILE}.bak"
    else
        echo "${MARKER_KEY}: ${MODE}" >> "$STATE_FILE"
    fi
fi
